// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzx4iOuHOjd1-m_ScQ_EiOQX8iGyy61Lc',
    appId: '1:807385749005:web:a0ebbdaadd330b31d86744',
    messagingSenderId: '807385749005',
    projectId: 'fruits-hub-d9581',
    authDomain: 'fruits-hub-d9581.firebaseapp.com',
    storageBucket: 'fruits-hub-d9581.firebasestorage.app',
    measurementId: 'G-5ZEVC4SE90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXWK-8b5g07Lf6fNNl9-gC_uFXXLBRfXc',
    appId: '1:807385749005:android:c56cd2a2c8909d11d86744',
    messagingSenderId: '807385749005',
    projectId: 'fruits-hub-d9581',
    storageBucket: 'fruits-hub-d9581.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqPrpu07wX7AmLg4rk2lF0MCUFHQLxsqM',
    appId: '1:807385749005:ios:cdbfd7a56429ec4ed86744',
    messagingSenderId: '807385749005',
    projectId: 'fruits-hub-d9581',
    storageBucket: 'fruits-hub-d9581.firebasestorage.app',
    androidClientId: '807385749005-9gh9e80emf5k0spr51jjs86kt5llq2qk.apps.googleusercontent.com',
    iosClientId: '807385749005-tfm1a0j0bt8cftttds9nisa8nrpm6pej.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqPrpu07wX7AmLg4rk2lF0MCUFHQLxsqM',
    appId: '1:807385749005:ios:cdbfd7a56429ec4ed86744',
    messagingSenderId: '807385749005',
    projectId: 'fruits-hub-d9581',
    storageBucket: 'fruits-hub-d9581.firebasestorage.app',
    androidClientId: '807385749005-9gh9e80emf5k0spr51jjs86kt5llq2qk.apps.googleusercontent.com',
    iosClientId: '807385749005-tfm1a0j0bt8cftttds9nisa8nrpm6pej.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzx4iOuHOjd1-m_ScQ_EiOQX8iGyy61Lc',
    appId: '1:807385749005:web:efbd86c480757eaed86744',
    messagingSenderId: '807385749005',
    projectId: 'fruits-hub-d9581',
    authDomain: 'fruits-hub-d9581.firebaseapp.com',
    storageBucket: 'fruits-hub-d9581.firebasestorage.app',
    measurementId: 'G-RKGG86V2HV',
  );
}
